# Generated by Django 4.0.6 on 2022-10-20 14:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingHour',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('start_time', models.JSONField(db_column='start_time')),
                ('end_time', models.JSONField(blank=True, db_column='end_time', null=True)),
                ('user', models.ForeignKey(db_column='User_Id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'WorkingHour',
                'managed': True,
            },
        ),
    ]
